title: Strata Titles Boards
url: https://www.stratatb.gov.sg
favicon: /images/Fav Icon & Logo/favicon-stb.ico
colors:
  primary-color: "#2e346c"
  secondary-color: "#253b64"
  media-colors:
    - title: media-color-one
      color: "#2a87af"
    - title: media-color-two
      color: "#de7019"
    - title: media-color-three
      color: "#2a87af"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: The Strata Titles Boards ("STB") are tribunals which handle
  disputes relating to strata-titled properties and orders on collective sales
  of such properties.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1gaaywk86e2om.amplifyapp.com
prod: https://master.d1gaaywk86e2om.amplifyapp.com
shareicon: /images/Fav Icon & Logo/favicon-stb.ico
is_government: true
facebook-pixel: ""
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: news-and-judgements
